name: syntanote
description: A smooth, music-inspired note and brainstorming app using SF Pro fonts
version: 1.0.0+1
publish_to: 'none'

environment:
 sdk: '>=3.0.0 <4.0.0'
 flutter: ^3.22.0

dependencies:
 flutter:
   sdk: flutter
 
 # Core Flutter packages
 cupertino_icons: ^1.0.6
 
 # Storage & File Management
 path_provider: ^2.1.1
 shared_preferences: ^2.2.2
 path: ^1.8.3
 
 # Sharing & URL handling
 share_plus: ^7.2.1
 url_launcher: ^6.2.5
 http: ^1.2.0
 
 # Audio Recording & Playback
 record: ^5.0.4
 just_audio: ^0.9.36
 audioplayers: ^5.2.1
 permission_handler: ^11.0.1
 
 # Firebase Backend
 firebase_core: ^2.25.0
 cloud_firestore: ^4.14.0
 firebase_storage: ^11.7.0
 firebase_storage_web: ^3.6.17

dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^3.0.1

flutter:
 uses-material-design: true

 fonts:
   - family: SF Pro Display
     fonts:
       - asset: assets/fonts/SF-Pro-Display-Thin.otf
         weight: 100
       - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
         weight: 200
       - asset: assets/fonts/SF-Pro-Display-Light.otf
         weight: 300
       - asset: assets/fonts/SF-Pro-Display-Regular.otf
         weight: 400
       - asset: assets/fonts/SF-Pro-Display-Medium.otf
         weight: 500
       - asset: assets/fonts/SF-Pro-Display-Semibold.otf
         weight: 600
       - asset: assets/fonts/SF-Pro-Display-Bold.otf
         weight: 700
       - asset: assets/fonts/SF-Pro-Display-Heavy.otf
         weight: 800
       - asset: assets/fonts/SF-Pro-Display-Black.otf
         weight: 900

   - family: SF Pro Text
     fonts:
       - asset: assets/fonts/SF-Pro-Text-Light.otf
         weight: 300
       - asset: assets/fonts/SF-Pro-Text-Regular.otf
         weight: 400
       - asset: assets/fonts/SF-Pro-Text-Medium.otf
         weight: 500
       - asset: assets/fonts/SF-Pro-Text-Semibold.otf
         weight: 600
       - asset: assets/fonts/SF-Pro-Text-Bold.otf
         weight: 700
       - asset: assets/fonts/SF-Pro-Text-Heavy.otf
         weight: 800